on:
  push:
    branches:
      - main

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      
      - name: Create .env file
        run: |
          echo "DB_DRIVER=${{ secrets.DB_DRIVER }}" >> .env
          echo "DB_URL=${{ secrets.DB_URL }}" >> .env
          echo "APP_HOST=${{ secrets.APP_HOST }}" >> .env
          echo "APP_PORT=${{ secrets.APP_PORT }}" >> .env
          echo "EMAIL_FROM=${{ secrets.EMAIL_FROM }}" >> .env
          echo "EMAIL_CODE=${{ secrets.EMAIL_CODE }}" >> .env
          echo "CLOUDINARY_URL=${{ secrets.CLOUDINARY_URL }}" >> .env
      
      - name: Create root.crt file
        run: echo "${{ secrets.CRT }}" >> root.crt
      
      - name: Validate .env and root.crt
        run: |
          test -f .env && echo ".env file exists"
          test -f root.crt && echo "root.crt file exists"
      
      - name: Login Docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-
      
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cicd:${{ github.sha }} .
      
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cicd:${{ github.sha }}
